CREATE EXTERNAL TABLE IF NOT EXISTS alltypes_100 (
id_0 int COMMENT 'Add a comment',
bool_col_0 boolean,
tinyint_col_0 tinyint,
smallint_col_0 smallint,
int_col_0 int,
bigint_col_0 bigint,
float_col_0 float,
double_col_0 double,
date_string_col_0 string,
string_col_0 string,
timestamp_col_0 timestamp,
id_1 int COMMENT 'Add a comment',
bool_col_1 boolean,
tinyint_col_1 tinyint,
smallint_col_1 smallint,
int_col_1 int,
bigint_col_1 bigint,
float_col_1 float,
double_col_1 double,
date_string_col_1 string,
string_col_1 string,
timestamp_col_1 timestamp,
id_2 int COMMENT 'Add a comment',
bool_col_2 boolean,
tinyint_col_2 tinyint,
smallint_col_2 smallint,
int_col_2 int,
bigint_col_2 bigint,
float_col_2 float,
double_col_2 double,
date_string_col_2 string,
string_col_2 string,
timestamp_col_2 timestamp,
id_3 int COMMENT 'Add a comment',
bool_col_3 boolean,
tinyint_col_3 tinyint,
smallint_col_3 smallint,
int_col_3 int,
bigint_col_3 bigint,
float_col_3 float,
double_col_3 double,
date_string_col_3 string,
string_col_3 string,
timestamp_col_3 timestamp,
id_4 int COMMENT 'Add a comment',
bool_col_4 boolean,
tinyint_col_4 tinyint,
smallint_col_4 smallint,
int_col_4 int,
bigint_col_4 bigint,
float_col_4 float,
double_col_4 double,
date_string_col_4 string,
string_col_4 string,
timestamp_col_4 timestamp,
id_5 int COMMENT 'Add a comment',
bool_col_5 boolean,
tinyint_col_5 tinyint,
smallint_col_5 smallint,
int_col_5 int,
bigint_col_5 bigint,
float_col_5 float,
double_col_5 double,
date_string_col_5 string,
string_col_5 string,
timestamp_col_5 timestamp,
id_6 int COMMENT 'Add a comment',
bool_col_6 boolean,
tinyint_col_6 tinyint,
smallint_col_6 smallint,
int_col_6 int,
bigint_col_6 bigint,
float_col_6 float,
double_col_6 double,
date_string_col_6 string,
string_col_6 string,
timestamp_col_6 timestamp,
id_7 int COMMENT 'Add a comment',
bool_col_7 boolean,
tinyint_col_7 tinyint,
smallint_col_7 smallint,
int_col_7 int,
bigint_col_7 bigint,
float_col_7 float,
double_col_7 double,
date_string_col_7 string,
string_col_7 string,
timestamp_col_7 timestamp,
id_8 int COMMENT 'Add a comment',
bool_col_8 boolean,
tinyint_col_8 tinyint,
smallint_col_8 smallint,
int_col_8 int,
bigint_col_8 bigint,
float_col_8 float,
double_col_8 double,
date_string_col_8 string,
string_col_8 string,
timestamp_col_8 timestamp,
id_9 int COMMENT 'Add a comment',
bool_col_9 boolean,
tinyint_col_9 tinyint,
smallint_col_9 smallint,
int_col_9 int,
bigint_col_9 bigint,
float_col_9 float,
double_col_9 double,
date_string_col_9 string,
string_col_9 string,
timestamp_col_9 timestamp,
id_10 int COMMENT 'Add a comment',
bool_col_10 boolean,
tinyint_col_10 tinyint,
smallint_col_10 smallint,
int_col_10 int,
bigint_col_10 bigint,
float_col_10 float,
double_col_10 double,
date_string_col_10 string,
string_col_10 string,
timestamp_col_10 timestamp

)

ROW FORMAT delimited fields terminated by ','  escaped by '\\'
STORED AS TEXTFILE
LOCATION '/user/admin/table_100';
